export enum ENotificationType {
  LOCATION = 'LOCATION',
  ACTIVITY = 'ACTIVITY',
  SYSTEM = 'SYSTEM',
  SOCIAL = 'SOCIAL',
  EVENT = 'EVENT',
}

export enum ENotificationSubType {
  FRIEND_MOVED = 'FRIEND_MOVED',
  FRIEND_NEAR = 'FRIEND_NEAR',
  LOCATION_SHARED = 'LOCATION_SHARED',
  STATUS_UPDATE = 'STATUS_UPDATE',
  SECURITY_ALERT = 'SECURITY_ALERT',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  PROXIMITY_MEETUP = 'PROXIMITY_MEETUP',
  MOMENT_NEW = 'MOMENT_NEW',
  MOMENT_REACTION = 'MOMENT_REACTION',
  NUDGE_RECEIVED = 'NUDGE_RECEIVED',
  INTIMACY_LEVEL_UP = 'INTIMACY_LEVEL_UP',
  EVENT = 'EVENT',
}
