export enum ENotificationType {
  LOCATION = 'LOCATION',
  ACTIVITY = 'ACTIVITY',
  SYSTEM = 'SYSTEM',
}

export enum ENotificationSubType {
  FRIEND_MOVED = 'FRIEND_MOVED',
  FRIEND_NEAR = 'FRIEND_NEAR',
  LOCATION_SHARED = 'LOCATION_SHARED',
  STATUS_UPDATE = 'STATUS_UPDATE',
  SECURITY_ALERT = 'SECURITY_ALERT',
}
